# Generated by Django 5.1.4 on 2025-01-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartmodel_phone_number'),
        ('library', '0002_alter_books_options_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library.books'),
        ),
    ]
